language: objective-c
osx_image: xcode12.2
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=DataManager.xcworkspace
  - IOS_FRAMEWORK_SCHEME="DataManager iOS"
  - OSX_FRAMEWORK_SCHEME="DataManager OSX"
  - TVOS_FRAMEWORK_SCHEME="DataManager tvOS"
  - WATCHOS_FRAMEWORK_SCHEME="DataManager watchOS"
  - IOS_SDK=iphonesimulator14.2
  - OSX_SDK=macosx11.0
  - TVOS_SDK=appletvsimulator14.2
  - WATCHOS_SDK=watchsimulator7.1
  matrix:
    - DESTINATION="OS=14.2,name=iPhone 8"           SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" POD_LINT="YES"
    - DESTINATION="arch=x86_64"                     SCHEME="$OSX_FRAMEWORK_SCHEME"     SDK="$OSX_SDK"     RUN_TESTS="YES" POD_LINT="NO"
    - DESTINATION="OS=14.0,name=Apple TV 4K"     SCHEME="$TVOS_FRAMEWORK_SCHEME"    SDK="$TVOS_SDK"    RUN_TESTS="YES" POD_LINT="NO"
    - DESTINATION="OS=7.0,name=Apple Watch Series 4 - 40mm"  SCHEME="$WATCHOS_FRAMEWORK_SCHEME" SDK="$WATCHOS_SDK" RUN_TESTS="NO"  POD_LINT="NO"
before_install:
  - rvm use $RVM_RUBY_VERSION
install:
  - bundle install --without=documentation
  - bundle exec pod repo update
  - bundle exec pod install
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug test | xcpretty -c;
    else
      xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug build | xcpretty -c;
    fi

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi
after_success:
 - bundle binstub slather
 - bin/slather coverage --binary-basename DataManager
